spring:
  application:
    name: vscan-api
    #архіви: 7z, rar, zip
    #Документи: doc, docx, latex, mdb, pdf, ppt, pptx, xls, xlsx, rtf
    #Images: bmp, emf, djvu, jpeg, jpg, png, tiff
    #Media: avi, mov, mp3, mp4, mp3g, wav, wma, wmv
    #Text: txt, xml, html
    allowed-file-extensions:
      - .7z
      - .rar
      - .zip
      - .doc
      - .docx
      - .latex
      - .mdb
      - .pdf
      - .ppt
      - .pptx
      - .xls
      - .xlsx
      - .rtf
      - .bmp
      - .emf
      - .djvu
      - .jpeg
      - .jpg
      - .png
      - .tiff
      - .avi
      - .mov
      - .mp3
      - .mp4
      - .mp3g
      - .wav
      - .wma
      - .wmv
      - .txt
      - .xml
      - .html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      sqs:
        region: eu-central-1
        queue:
          file-upload-queue: file-upload-queue-test
          seg-log-queue: seg-log-queue-test
      s3:
        region: eu-central-1
        dirty-bucket: vscan-api-dirty-storage-test
      dynamodb:
        region: eu-central-1
        file-scan-result-table: FileScanResults-test
  mail:
    port: 2525
    host: mriya.organic-invest-llc.com #change in SSM
    from: noreply@mriya.organic-invest-llc.com
    to: seg@mriya.organic-invest-llc.com
    subject: "Scanning file. File id: "


management:
  endpoints:
    web:
      exposure:
        include: info, health
      base-path: /
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false #remove after fixing smtp server

logging:
  level:
    com.dataslab.vscan: debug
    org.springframework: info

tcp:
  server:
    port: 8081

